Support Java 11 and add trino plugin
apache/ranger pull request #106
Opened 2021-06-11 08:23 UTC by jles01

Supoort for java 11 and trino plugin

2021-08-01 20:22 UTC, exolab commented
Is this still being worked on?

2021-08-03 09:40 UTC, jles01 commented
Hi, 

It is working, there will be minor changes, to make it build with success. Also in other PR there will be added Trino support for Hive security, so they can be reused

2021-08-11 07:32 UTC, adnanhemani commented
Hi, isn't the current `presto` plugin the one that should work for Trino as well? I understand after the Trino fork, there may need to be some package name changing, but for the most part there doesn't need to be any logical difference or use for the old "presto" plugin. Shouldn't we just rename everything in the Presto plugin and make it the official support for Trino?

2021-08-11 09:41 UTC, jles01 commented
> Hi, isn't the current `presto` plugin the one that should work for Trino as well? I understand after the Trino name change, there may need to be some package name changing, but for the most part there doesn't need to be any logical difference or use for the old "presto" plugin. Shouldn't we just rename everything in the Presto plugin and make it the official support for Trino?

From my knowledge presto still exists and will be continued. Should we move that users outside apache ranger ? I would not be so sure. We can have both or only Trino, the question would be how much "presto ranger" users out there

2021-08-11 20:32 UTC, adnanhemani commented
From what I gathered, it seemed like PrestoDB was _not_ supported by our current presto plugin and that a new PrestoDB plugin would be required that would have slightly different logic. If that's correct, I'd think that it makes more sense to say the current Ranger version (v2.1.0) is the latest version supported for all Trino versions before the renaming and the next Ranger version will have support for all Trino versions past the Trino renaming - and that we should change the current presto plugin to be the official Trino plugin

2021-08-11 20:48 UTC, adnanhemani commented
Actually, I just read this thread: [](hhttps://issues.apache.org/jira/browse/RANGER-3182?focusedCommentId=17311823&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17311823). Seems like a new Trino plugin will be required - but not for the issues we were discussing 😁

Watching thread for progress.

2021-08-12 23:44 UTC, adnanhemani commented
I think we can keep it for now 🤷 we can remove in a later PR, if required?

2021-09-21 20:53 UTC, martin-g commented on kms/src/main/java/org/apache/hadoop/crypto/key/RangerSafenetKeySecure.java
> +			}else*/ if(javaVersion == 9 || javaVersion == 10 || javaVersion == 11){
See https://github.com/apache/ranger/pull/96 for better solution

2021-09-30 06:43 UTC, RameshByndoor requested changes
Did you check default servicedef, you need to add trino as well.

2021-10-08 10:25 UTC, jerryleooo commented
Encountered following error

```
+ Fri Oct  8 18:21:12 +08 2021 : Saving lib file: /opt/presto/lib/validation-api-2.0.1.Final.jar to /opt/presto/lib/.validation-api-2.0.1.Final.jar.20211008182112 ...
Unable to store password in non-plain text format. Error: [SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
        at org.apache.hadoop.metrics2.lib.MutableMetricsFactory.getName(MutableMetricsFactory.java:134)
        at org.apache.hadoop.metrics2.lib.MutableMetricsFactory.getInfo(MutableMetricsFactory.java:130)
        at org.apache.hadoop.metrics2.lib.MutableMetricsFactory.newForField(MutableMetricsFactory.java:45)
        at org.apache.hadoop.metrics2.lib.MetricsSourceBuilder.add(MetricsSourceBuilder.java:147)
        at org.apache.hadoop.metrics2.lib.MetricsSourceBuilder.<init>(MetricsSourceBuilder.java:69)
        at org.apache.hadoop.metrics2.lib.MetricsAnnotations.newSourceBuilder(MetricsAnnotations.java:43)
        at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.register(MetricsSystemImpl.java:223)
        at org.apache.hadoop.metrics2.MetricsSystem.register(MetricsSystem.java:71)
        at org.apache.hadoop.security.UserGroupInformation$UgiMetrics.create(UserGroupInformation.java:149)
        at org.apache.hadoop.security.UserGroupInformation.<clinit>(UserGroupInformation.java:265)
        at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3614)
        at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3604)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3441)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:524)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
        at org.apache.hadoop.security.alias.JavaKeyStoreProvider.initFileSystem(JavaKeyStoreProvider.java:89)
        at org.apache.hadoop.security.alias.AbstractJavaKeyStoreProvider.<init>(AbstractJavaKeyStoreProvider.java:85)
        at org.apache.hadoop.security.alias.JavaKeyStoreProvider.<init>(JavaKeyStoreProvider.java:49)
        at org.apache.hadoop.security.alias.JavaKeyStoreProvider.<init>(JavaKeyStoreProvider.java:41)
        at org.apache.hadoop.security.alias.JavaKeyStoreProvider$Factory.createProvider(JavaKeyStoreProvider.java:100)
        at org.apache.hadoop.security.alias.CredentialProviderFactory.getProviders(CredentialProviderFactory.java:73)
        at org.apache.ranger.credentialapi.CredentialReader.getDecryptedString(CredentialReader.java:74)
        at org.apache.ranger.credentialapi.buildks.createCredential(buildks.java:87)
        at org.apache.ranger.credentialapi.buildks.main(buildks.java:41)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 24 more]
Exiting plugin installation
```

Java version: 15.0.1

2022-06-13 19:40 UTC, koby-kramer-shopify commented
Can't this be closed now since Trino support was added?

2022-11-17 07:58 UTC, preetsindhal commented
Hi, can anyone share how to build the Trino plugin with 2.3 release i have tried the following but no tar file was created for trino plugin.

mvn -Pall -DskipTests=true clean compile package install 

mvn -Pranger-jdk11 -DskipTests=true clean compile package install

mvn -DskipTests=true clean compile package install assembly:assembly  - fails with error

I tried building it as explained here https://issues.apache.org/jira/browse/RANGER-3755 but no luck, getting the same errors as last comment on this jira issue.

thanks.

2023-05-15 19:58 UTC, esselius commented
> Hi, can anyone share how to build the Trino plugin with 2.3 release i have tried the following but no tar file was created for trino plugin.
> 
> mvn -Pall -DskipTests=true clean compile package install
> 
> mvn -Pranger-jdk11 -DskipTests=true clean compile package install
> 
> mvn -Pranger-jdk11 -DskipTests=true clean compile package install assembly:assembly - fails with error
> 
> I tried building it as explained here [issues.apache.org/jira/browse/RANGER-3755](https://issues.apache.org/jira/browse/RANGER-3755) but no luck, getting the same errors as last comment on this jira issue.
> 
> thanks.

I wasted many days on this, but turns out you need to disable the distro linux profile and pick a few modules manually to make it work:

```
$ mvn clean package -DskipTests -P ranger-trino-plugin,-linux -am -pl distro,plugin-trino,ranger-trino-plugin-shim,agents-installer,credentialbuilder
```

2023-08-02 16:48 UTC, floyola commented
I'm trying to install the plugin, but I'm getting the following error
```
2023-08-01T18:35:24.368Z	INFO	main	io.trino.security.AccessControlManager	-- Loading system access control etc/access-control.properties --
2023-08-01T18:35:24.368Z	ERROR	main	io.trino.server.Server	Access control 'ranger' is not registered: /code/var/presto/data/etc/access-control.properties
```

These are the plugin logs
```
+ Tue Aug  1 20:13:42 UTC 2023 : trino: lib folder=/code/presto/presto/lib conf folder=/code/presto/presto/etc
+ Tue Aug  1 20:13:42 UTC 2023 : Saving current config file: /code/presto/presto/etc/ranger-policymgr-ssl.xml to /code/presto/presto/etc/.ranger-policymgr-ssl.xml.20230801-201342 ...
+ Tue Aug  1 20:13:42 UTC 2023 : Saving current config file: /code/presto/presto/etc/ranger-trino-audit.xml to /code/presto/presto/etc/.ranger-trino-audit.xml.20230801-201342 ...
+ Tue Aug  1 20:13:43 UTC 2023 : Saving current config file: /code/presto/presto/etc/ranger-trino-security.xml to /code/presto/presto/etc/.ranger-trino-security.xml.20230801-201342 ...
+ Tue Aug  1 20:13:43 UTC 2023 : Saving lib file: /code/presto/presto/lib/guice-5.1.0.jar to /code/presto/presto/lib/.guice-5.1.0.jar.20230801201343 ...
+ Tue Aug  1 20:13:43 UTC 2023 : Saving lib file: /code/presto/presto/lib/javax.annotation-api-1.3.2.jar to /code/presto/presto/lib/.javax.annotation-api-1.3.2.jar.20230801201343 ...
+ Tue Aug  1 20:13:43 UTC 2023 : Saving lib file: /code/presto/presto/lib/javax.inject-1.jar to /code/presto/presto/lib/.javax.inject-1.jar.20230801201343 ...
+ Tue Aug  1 20:13:43 UTC 2023 : Saving lib file: /code/presto/presto/lib/validation-api-2.0.1.Final.jar to /code/presto/presto/lib/.validation-api-2.0.1.Final.jar.20230801201343 ...
Property -Dlogback.configurationFile added successfully with : '/code/presto/presto/etc/trino-ranger-plugin-logback.xml'
backup of /code/presto/presto/etc/access-control.properties to /code/presto/presto/etc/.access-control.properties.20230801201343 ...
Add or Update properties file: [/code/presto/presto/etc/access-control.properties] ...
Property access-control.name updated successfully with : 'ranger'
Linking config files
Ranger Plugin for trino has been enabled.
```

And the access-control.properties only contains `access-control.name=ranger`

Does anyone have any idea what might be going on?

I'm using Ranger 2.4.0 and Trino 405

2023-09-12 13:58 UTC, dshershov commented
Hi @esselius ! Your solution is very close to what I need!
Unfortunately this is not working for me on 2.4.0 ranger version with 17ojdk. Maybe you have some ideas how I can fix that.
I tried build trino plugin with 414 version of trino with the next command:
`JAVA_HOME=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home && mvn clean package -DskipTests -P ranger-trino-plugin,-linux(or -mac) -am -pl agents-audit,agents-common,agents-cred,agents-installer,credentialbuilder,ranger-plugin-classloader,ranger-util,plugin-trino,ranger-trino-plugin-shim`

```
[INFO] Reactor Summary for ranger 2.4.0:
[INFO]
[INFO] ranger ............................................. SUCCESS [  0.897 s]
[INFO] Credential Support ................................. SUCCESS [  1.974 s]
[INFO] Audit Component .................................... SUCCESS [  2.799 s]
[INFO] ranger-plugin-classloader .......................... SUCCESS [  0.906 s]
[INFO] Common library for Plugins ......................... SUCCESS [  5.663 s]
[INFO] Installer Support Component ........................ SUCCESS [  0.513 s]
[INFO] Credential Builder ................................. SUCCESS [  1.403 s]
[INFO] Ranger Util ........................................ SUCCESS [  1.196 s]
[INFO] Trino Security Plugin .............................. SUCCESS [  2.398 s]
[INFO] Trino Security Plugin Shim ......................... SUCCESS [  1.300 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```
But archive was missing into target directory.
Thanks a lot for your ideas!

2024-01-26 11:44 UTC, tarekabouzeid commented
> Hi @esselius ! Your solution is very close to what I need! Unfortunately this is not working for me on 2.4.0 ranger version with 17ojdk. Maybe you have some ideas how I can fix that. I tried build trino plugin with 414 version of trino with the next command: `JAVA_HOME=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home && mvn clean package -DskipTests -P ranger-trino-plugin,-linux(or -mac or -"mac os x") -am -pl agents-audit,agents-common,agents-cred,agents-installer,credentialbuilder,ranger-plugin-classloader,ranger-util,plugin-trino,ranger-trino-plugin-shim`
> 
> ```
> [INFO] Reactor Summary for ranger 2.4.0:
> [INFO]
> [INFO] ranger ............................................. SUCCESS [  0.897 s]
> [INFO] Credential Support ................................. SUCCESS [  1.974 s]
> [INFO] Audit Component .................................... SUCCESS [  2.799 s]
> [INFO] ranger-plugin-classloader .......................... SUCCESS [  0.906 s]
> [INFO] Common library for Plugins ......................... SUCCESS [  5.663 s]
> [INFO] Installer Support Component ........................ SUCCESS [  0.513 s]
> [INFO] Credential Builder ................................. SUCCESS [  1.403 s]
> [INFO] Ranger Util ........................................ SUCCESS [  1.196 s]
> [INFO] Trino Security Plugin .............................. SUCCESS [  2.398 s]
> [INFO] Trino Security Plugin Shim ......................... SUCCESS [  1.300 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> ```
> 
> But archive was missing into target directory. Thanks a lot for your ideas!

Hi,

Did you manage to get it to work with this Trino version?


Thanks

2024-08-08 14:25 UTC, DatumWorld commented
> > Hi, can anyone share how to build the Trino plugin with 2.3 release i have tried the following but no tar file was created for trino plugin.
> > mvn -Pall -DskipTests=true clean compile package install
> > mvn -Pranger-jdk11 -DskipTests=true clean compile package install
> > mvn -Pranger-jdk11 -DskipTests=true clean compile package install assembly:assembly - fails with error
> > I tried building it as explained here [issues.apache.org/jira/browse/RANGER-3755](https://issues.apache.org/jira/browse/RANGER-3755) but no luck, getting the same errors as last comment on this jira issue.
> > thanks.
> 
> I finally figured out how to do this, turns out you need to disable the distro linux profile and pick a few modules manually to make it work:
> 
> ```
> $ cd apache-ranger-2.4.0
> $ mvn clean package -DskipTests -P ranger-trino-plugin,-linux -am -pl distro,plugin-trino,ranger-trino-plugin-shim,agents-installer,credentialbuilder
> ```
> 
> The artifact lands @ `target/ranger-2.4.0-trino-plugin.tar.gz`
> 
> The problem was that the linux profile in the distro module implicitly activates and overrides the ranger-trino-plugin profile maven config etc

Could anyone share how to build it with the 2.5 release? It does not work

2024-08-11 14:05 UTC, DatumWorld commented
@esselius Hi!  any idea with the 2.5 release? Thanks

> > > Hi, can anyone share how to build the Trino plugin with 2.3 release i have tried the following but no tar file was created for trino plugin.
> > > mvn -Pall -DskipTests=true clean compile package install
> > > mvn -Pranger-jdk11 -DskipTests=true clean compile package install
> > > mvn -Pranger-jdk11 -DskipTests=true clean compile package install assembly:assembly - fails with error
> > > I tried building it as explained here [issues.apache.org/jira/browse/RANGER-3755](https://issues.apache.org/jira/browse/RANGER-3755) but no luck, getting the same errors as last comment on this jira issue.
> > > thanks.
> > 
> > 
> > I finally figured out how to do this, turns out you need to disable the distro linux profile and pick a few modules manually to make it work:
> > ```
> > $ cd apache-ranger-2.4.0
> > $ mvn clean package -DskipTests -P ranger-trino-plugin,-linux -am -pl distro,plugin-trino,ranger-trino-plugin-shim,agents-installer,credentialbuilder
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The artifact lands @ `target/ranger-2.4.0-trino-plugin.tar.gz`
> > The problem was that the linux profile in the distro module implicitly activates and overrides the ranger-trino-plugin profile maven config etc
> 
> Could anyone share how to build it with the 2.5 release? It does not work

2024-08-11 17:23 UTC, mneethiraj commented
> Could anyone share how to build it with the 2.5 release? It does not work

@DatumWorld  - Trino plugin implementation is removed from Ranger git repo and is being moved to Trino git repo; this effort is tracked by [RANGER-4810](https://issues.apache.org/jira/browse/RANGER-4810).

Please review the [PR in Trino](https://github.com/trinodb/trino/pull/22675) repo.

2025-01-19 02:26 UTC, kumaab commented
Closing the PR, Trino plugin implementation has moved to the Trino repo.

2025-01-19 02:26 UTC, closed without merging